baseURL = "https://www.josehu.com/intention-base/"
languageCode = "en-us"
title = "App Intention Base"

theme = "hugo-book"

[params]
BookSection = "*"
BookRepo = "https://github.com/josehu07/intention-base"
BookCommitPath = "commit"
BookEditPath = "edit/main"
